# Generated by Django 4.0.4 on 2022-04-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=100)),
                ('objet', models.TextField()),
                ('region', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=200)),
            ],
        ),
    ]
