# Generated by Django 4.0.4 on 2022-04-20 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ao', '0001_initial'),
        ('prix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ao_Prix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pu', models.FloatField()),
                ('qty', models.IntegerField()),
                ('ao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ao.aos')),
                ('prix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prix.prixs')),
            ],
        ),
    ]
