# Generated by Django 4.0.4 on 2022-04-20 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('secteur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('secteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secteur.secteurs')),
            ],
        ),
    ]
